# Generated by Django 5.2.6 on 2025-09-08 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timesent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
